# Site settings
#google_analytics: UA-NNNNNNNN-N

url: "https://theinemann.de"

header_pages:
  - index.md
  - thoughts.md
  - contact.md

#footer:

style: light

#style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

exclude:
  - genealogy-viewer/
